/*
 * Copyright (C) 2014 Nathan
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package interfaces;

import javax.swing.DefaultComboBoxModel;
import meta.LineNote;

/**
 *
 * @author Nathan
 */
public class AddLineNote extends javax.swing.JDialog {
    private LineNote note;
    private String characterName;
    private String error;
    DefaultComboBoxModel characterList;
    /**
     * Creates new form AddLineNote
     */
    public AddLineNote(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public AddLineNote(java.awt.Frame parent, boolean modal, DefaultComboBoxModel characterList) {
        super(parent, modal);
        this.characterList = characterList;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        notFilledOptionPane = new javax.swing.JOptionPane();
        lineNoteOptionPane = new javax.swing.JOptionPane();
        characterLabel = new javax.swing.JLabel();
        pageLabel = new javax.swing.JLabel();
        pageTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lineNoteEditor = new javax.swing.JEditorPane();
        RBWrongWord = new javax.swing.JRadioButton();
        RBAdded = new javax.swing.JRadioButton();
        RBJumpedLine = new javax.swing.JRadioButton();
        RBWrongOrder = new javax.swing.JRadioButton();
        RBCalledLine = new javax.swing.JRadioButton();
        RBDropped = new javax.swing.JRadioButton();
        RBCheckLine = new javax.swing.JRadioButton();
        clearButton = new javax.swing.JButton();
        addNoteButton = new javax.swing.JButton();
        characterSelector = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        characterLabel.setText("Character:");

        pageLabel.setText("Page:");

        pageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pageTextFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lineNoteEditor);

        buttonGroup1.add(RBWrongWord);
        RBWrongWord.setText("Wrong Word");
        RBWrongWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBWrongWordActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBAdded);
        RBAdded.setText("Added");
        RBAdded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBAddedActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBJumpedLine);
        RBJumpedLine.setText("Jumped Line");
        RBJumpedLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBJumpedLineActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBWrongOrder);
        RBWrongOrder.setText("Wrong Order");
        RBWrongOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBWrongOrderActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBCalledLine);
        RBCalledLine.setText("Called Line");

        buttonGroup1.add(RBDropped);
        RBDropped.setText("Dropped");
        RBDropped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBDroppedActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBCheckLine);
        RBCheckLine.setText("Check Line");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        addNoteButton.setText("Add Note");
        addNoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoteButtonActionPerformed(evt);
            }
        });

        characterSelector.setModel(characterList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(characterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(characterSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addNoteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBJumpedLine)
                            .addComponent(RBWrongWord)
                            .addComponent(RBAdded))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBWrongOrder)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBCheckLine)
                                    .addComponent(RBDropped)))
                            .addComponent(RBCalledLine))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addNoteButton, clearButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characterLabel)
                    .addComponent(pageLabel)
                    .addComponent(pageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(characterSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBWrongWord)
                    .addComponent(RBWrongOrder)
                    .addComponent(RBDropped))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBAdded)
                    .addComponent(RBCalledLine)
                    .addComponent(RBCheckLine))
                .addGap(6, 6, 6)
                .addComponent(RBJumpedLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(addNoteButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pageTextFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearText();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void addNoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoteButtonActionPerformed
        if (lineNoteEditor == null || pageTextField == null || whichRadioButton() == null) {
            notFilledOptionPane.showMessageDialog(null,
            "You need to fill out all the fields.",
            "Error",
            notFilledOptionPane.ERROR_MESSAGE);
            
            return;
        }
        
        characterName = characterSelector. getSelectedItem().toString();
        String line = lineNoteEditor.getText();
        String pageNum = pageTextField.getText();
        String mistake = whichRadioButton().getText();
        note = new LineNote(line, error, pageNum, mistake);
        
        clearText();
        super.dispose();
    }//GEN-LAST:event_addNoteButtonActionPerformed

    private void RBWrongWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBWrongWordActionPerformed
        error = lineNoteOptionPane.showInputDialog(null, 
            "Enter the error.", 
            "Enter Error",
            lineNoteOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RBWrongWordActionPerformed

    private void RBWrongOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBWrongOrderActionPerformed
        error = lineNoteOptionPane.showInputDialog(null, 
            "Enter the error, putting the pipe\n"
                    + "symbol \"|\" in between the phrases", 
            "Enter Error",
            lineNoteOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RBWrongOrderActionPerformed

    private void RBDroppedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBDroppedActionPerformed
        error = lineNoteOptionPane.showInputDialog(null, 
            "Enter the dropped word.", 
            "Enter Error",
            lineNoteOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RBDroppedActionPerformed

    private void RBAddedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBAddedActionPerformed
        error = lineNoteOptionPane.showInputDialog(null, 
            "Enter the added word(s).", 
            "Enter Error",
            lineNoteOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RBAddedActionPerformed

    private void RBJumpedLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBJumpedLineActionPerformed
        error = lineNoteOptionPane.showInputDialog(null, 
            "Enter the last line that was jumped over.", 
            "Enter Error",
            lineNoteOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_RBJumpedLineActionPerformed

    public LineNote getLineNote() {
        return note;
    }
    
    public String getCharacterName() {
        return characterName;
    }
    
    private javax.swing.JRadioButton whichRadioButton() {
        if (RBWrongWord.isSelected()) {
            return RBWrongWord;
        } else if (RBWrongOrder.isSelected()) {
            return RBWrongOrder;
        } else if (RBDropped.isSelected()) {
            return RBDropped;
        } else if (RBAdded.isSelected()) {
            return RBAdded;
        } else if (RBCalledLine.isSelected()) {
            return RBCalledLine;
        } else if (RBCheckLine.isSelected()) {
            return RBCheckLine;
        } else if (RBJumpedLine.isSelected()) {
            return RBJumpedLine;
        }
        return null;
    }
    
    private void clearText() {
        pageTextField.setText("");
        lineNoteEditor.setText(""); 
        buttonGroup1.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBAdded;
    private javax.swing.JRadioButton RBCalledLine;
    private javax.swing.JRadioButton RBCheckLine;
    private javax.swing.JRadioButton RBDropped;
    private javax.swing.JRadioButton RBJumpedLine;
    private javax.swing.JRadioButton RBWrongOrder;
    private javax.swing.JRadioButton RBWrongWord;
    private javax.swing.JButton addNoteButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel characterLabel;
    private javax.swing.JComboBox characterSelector;
    private javax.swing.JButton clearButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane lineNoteEditor;
    private javax.swing.JOptionPane lineNoteOptionPane;
    private javax.swing.JOptionPane notFilledOptionPane;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JTextField pageTextField;
    // End of variables declaration//GEN-END:variables
}
